spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gps-batch
    username: root
    password: Mps@1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        diaect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    servlet:
      path: /v1
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS

